### PR TITLE
Update to Rails 7.1

### PR DESCRIPTION
**Pull request by tacerus**
Similar to https://github.com/openSUSE/paste-o-o/pull/177, but updates schema and container dependencies as well. How to generate vendor/?

### CODE REVIEW

**Comment by hellcp** [comment]
Running `docker-compose run web bundle install` should pull in the contents of the vendor

**Comment by hellcp** [comment]
Seems that the tests are failing, we might need to use [`freeze_time`](https://api.rubyonrails.org/v5.2.4/classes/ActiveSupport/Testing/TimeHelpers.html#method-i-freeze_time)

**Comment by hellcp** [comment]
Seems like rubocop passes though, the only thing left is haml_lints from linters

**Comment by tacerus** [comment]
Yes, I did apply `haml-lint -a` as well, but `SpaceInsideHashAttributes` it does not resolve automatically. If I resolve it manually by adding a space after `{`, then rubocop complains about the space.

**Comment by tacerus** [comment]
Maybe to explain better by an example:


```
diff --git a/app/views/auths/index.html.haml b/app/views/auths/index.html.haml
index d481335..687a79f 100644
--- a/app/views/auths/index.html.haml
+++ b/app/views/auths/index.html.haml
@@ -20 +20 @@
-            %button.btn.btn-secondary{type: 'button', 'aria-expanded': 'false',
+            %button.btn.btn-secondary{ type: 'button', 'aria-expanded': 'false',
@@ -22 +22 @@
-                                      title: t(:options)}
+                                      title: t(:options) }
```

Yields:

```
app/views/auths/index.html.haml:20 [W] RuboCop: Layout/SpaceInsideParens: Space inside parentheses detected.
app/views/auths/index.html.haml:21 [W] RuboCop: Layout/ArgumentAlignment: Align the arguments of a method call if they span more than one line.
app/views/auths/index.html.haml:21 [W] RuboCop: Layout/HashAlignment: Align the keys of a hash literal if they span more than one line.
app/views/auths/index.html.haml:22 [W] RuboCop: Layout/ArgumentAlignment: Align the arguments of a method call if they span more than one line.
app/views/auths/index.html.haml:22 [W] RuboCop: Layout/HashAlignment: Align the keys of a hash literal if they span more than one line.
app/views/auths/index.html.haml:22 [W] RuboCop: Layout/SpaceInsideParens: Space inside parentheses detected.
```

But:

```
            %button.btn.btn-secondary{type: 'button', 'aria-expanded': 'false',
                                      'data-bs-toggle': 'dropdown',
                                      title: t(:options)}
```

Yields:

```
app/views/auths/index.html.haml:20 [W] SpaceInsideHashAttributes: Hash attribute should start with one space after the opening brace
app/views/auths/index.html.haml:20 [W] SpaceInsideHashAttributes: Hash attribute should end with one space before the closing brace or be on its own line
```

**Comment by tacerus** [comment]
Ah, thank you!

**Comment by hellcp** [comment]
I pushed a commit to hopefully fix the circular dependency

**Comment by tacerus** [comment]
Linting passes now, but I'm stuck with the rspec tests. Where do you mean should `freeze_time` be used? In paste.rb?

**Comment by hellcp** [comment]
In the tests, to make sure we are dealing with the same time frame inside the tests

**Comment by hellcp** [comment]
I guess for the rest you can just use `.delete('updated_at')` to ignore that, since it's not exactly required

**Comment by tacerus** [comment]
Thanks, here, it works fine:

```
--- a/spec/jobs/pastes_cleanup_job_spec.rb
+++ b/spec/jobs/pastes_cleanup_job_spec.rb
@@ -6,0 +7 @@ RSpec.describe PastesCleanupJob do
+
@@ -13,0 +15 @@ RSpec.describe PastesCleanupJob do
+      freeze_time
@@ -24,0 +27,5 @@ RSpec.describe PastesCleanupJob do
+
+    after do
+      travel_back
+    end
+
```

But not in `pastes_spec.rb` ...

**Comment by tacerus** [comment]
Hm, now I get a lot of errors concluding with "stack level to deep".

**Comment by tacerus** [comment]
All green now! What do you think?

**Pull request merged**
